### ISSUE TITLE
Modify subjects on emails sent by authors or to authors.

### ISSUE THREAD

**Issue by balhar-jakub** [CSLD/CSLD#175]

**Comment by mhavelka** [comment]
I am not sure if it's same issue or not, but sender of e-mail should be set to actual user, not to "larpovadatabaze@gmail.com".

Please, provide me short feedback if I should create new issue or if you ackonwledged this one. Thanks.

**Comment by balhar-jakub** [comment]
I am afraid that changing from of the email isn't actually possible at the moment. 
We would have to have our own mail server and even then this would have lots of issues.
