### ISSUE TITLE
Add "featured" column into csld_photo table

### ISSUE THREAD

**Issue by mhavelka** [CSLD/CSLD#178]
In the future it will generate photos on homepage based on this flag (if featured cell is set to 1 or 0).

I want to complete photo revision till 31th January and I will flag the photos during this revision, so due date is ideal till this weekend. Is it possible please?

@balhar-jakub

**Comment by balhar-jakub** [comment]
The structure of the database was updated. I don't yet know how to implement graphical interface for this. 
So for now, you will have to set it up in the database.

**Comment by balhar-jakub** [comment]
It is possible now to set this on the photo detail  on game detail page via buttons.

**Comment by mhavelka** [comment]
This right has to be only for moderators. Is it possible please?

**Comment by balhar-jakub** [comment]
Sure, but at least the possibility to hide the photo should belong to the authors of the game as well.
