### ISSUE TITLE
Add coupling table photo-game to DB

### ISSUE THREAD

**Issue by mhavelka** [CSLD/CSLD#179]
This table will be used for coupling cover photos with game. Another solution is to add columnd with photo id to csld_game table. Implementations details are up to you.

**Comment by mhavelka** [comment]
As I see from DB, this one is not closed. Could you please describe how it is implemented?

**Comment by balhar-jakub** [comment]
Why  do you need it? One photo won't belong to two games.

2015-01-25 11:23 GMT+01:00 Michal Havelka <notifications@github.com>:

**Comment by balhar-jakub** [comment]
And the photo is this table, it is connection among image and game.

2015-01-25 11:36 GMT+01:00 Jakub Balhar <balhar.jakub@gmail.com>:

**Comment by mhavelka** [comment]
I suppose there is missunderstanding. What we need on new UI design is to mark(flag) exactly one photo, which will be cover photo of the game.

Current implementation is pairing photo-game (which photos will be showed by which game). We need "upgrade" which of these photos will be cover photo.

Is it now more understandable please?

**Comment by balhar-jakub** [comment]
There is one such picture. Therefore it was added to the game table. You
dont need aditional table for this.
Dne 25.1.2015 17:48 "Michal Havelka" <notifications@github.com> napsal(a):
